- name: remote server
  hosts: all
  vars:
    profile: "{{ profile | default('') }}"
  tasks:
    - name: Mostrar el valor de profile
      debug:
        msg: "El valor de profile es '{{ profile }}'"

    - name: create file for dev and uat
      file:
        path: /tmp/ansible_test.txt
        state: touch
      when: profile in ['dev', 'uat']

    - name: create file for prd
      file:
        path: /tmp/ansible_prd.txt
        state: touch
      when: profile == "prd"