---
- name: remote server
  hosts: all
  tasks:
    - name: Actualizar paquetes en el servidor remoto
      become: yes
      yum:
        name: "*"
        state: latest

    - name: create file 
      file:
        path: /tmp/ansible_test.txt
        state: touch